### ISSUE TITLE
undefined method `exists?' for File:Class

### ISSUE THREAD

**Issue by gustavogsimas** [state-machines/state_machines#103]
Gem not working with ruby 3.2:

/.rvm/gems/ruby-3.2.3/gems/state_machine-1.2.0/lib/state_machine/integrations/base.rb:81:in `locale_path': undefined method `exists?' for File:Class (NoMethodError)

          path if File.exists?(path)
                      ^^^^^^^^

File.exists now has been changed to File.exist?

Probably this gem is not being maintened anymore, but to register the issue.
